name: ANTLR4 testsuite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: rrevenantt/antlr4
          ref: rust-target
          submodules: true
      - run:  git fetch origin $GITHUB_REF
        working-directory: runtime/Rust
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly-2020-12-23
          default: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run : mvn -DskipTests install -q
      - name : Maven tests
        run: |
          mvn test -Dtest=rust.* -q
          rc=$?;
          cat target/surefire-reports/*.dumpstream || true;
          exit $rc
        working-directory: runtime-testsuite
      - uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          name: antlr-tool
          path: tool/target/antlr4-4.8-2-SNAPSHOT-complete.jar

        
